spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  security:
    user:
      name: ${TEST_ADMIN_ID}      # 테스트할 때 쓸 아이디 (원하는 대로 변경 가능)
      password: ${TEST_ADMIN_PW}   # 테스트할 때 쓸 비밀번호 (원하는 대로 변경 가능)

# Superbase 설정 (별도 계층)
supabase:
  url: "https://hiqyqzmyoxafmrrspntv.supabase.co"
  service-key: ${DB_KEY}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true